### ISSUE TITLE
Ubuntu 16.04上无法启动

### ISSUE THREAD

**Issue by ghost** [sbwtw/sos#1]
你好，我想学习一下您的操作系统。我按照readme上说的进行了操作，生成了sos.iso，但是无法用虚拟机启动（VirtualBox和qemu）。系统是ubuntu 16.04 GCC 5.4.0 cmake 3.12.0

**Comment by sbwtw** [comment]
@zhangzp9970 无法启动的话有什么现象呢？在 build 过程中有没有什么报错？

**Comment by ghost** [comment]
zzp@zzp-HP-ubuntu:~/sos-master$ mkdir build
zzp@zzp-HP-ubuntu:~/sos-master$ cd build/
zzp@zzp-HP-ubuntu:~/sos-master/build$ cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_ASM_COMPILER=g++ ..
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/g++
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zzp/sos-master/build

**Comment by ghost** [comment]
$ make
/usr/local/bin/cmake -H/home/zzp/sos-master -B/home/zzp/sos-master/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/zzp/sos-master/build/CMakeFiles /home/zzp/sos-master/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/zzp/sos-master/build'
make -f CMakeFiles/sos_kernel.dir/build.make CMakeFiles/sos_kernel.dir/depend
make[2]: Entering directory '/home/zzp/sos-master/build'
cd /home/zzp/sos-master/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/zzp/sos-master /home/zzp/sos-master /home/zzp/sos-master/build /home/zzp/sos-master/build /home/zzp/sos-master/build/CMakeFiles/sos_kernel.dir/DependInfo.cmake --color=
Scanning dependencies of target sos_kernel
make[2]: Leaving directory '/home/zzp/sos-master/build'
make -f CMakeFiles/sos_kernel.dir/build.make CMakeFiles/sos_kernel.dir/build
make[2]: Entering directory '/home/zzp/sos-master/build'
[  7%] Building ASM object CMakeFiles/sos_kernel.dir/asm/interrupt_stubs.s.o
/usr/bin/g++  -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include   -m32 -o CMakeFiles/sos_kernel.dir/asm/interrupt_stubs.s.o -c /home/zzp/sos-master/asm/interrupt_stubs.s
[ 14%] Building ASM object CMakeFiles/sos_kernel.dir/asm/loader.s.o
/usr/bin/g++  -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include   -m32 -o CMakeFiles/sos_kernel.dir/asm/loader.s.o -c /home/zzp/sos-master/asm/loader.s
[ 21%] Building ASM object CMakeFiles/sos_kernel.dir/asm/printf.s.o
/usr/bin/g++  -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include   -m32 -o CMakeFiles/sos_kernel.dir/asm/printf.s.o -c /home/zzp/sos-master/asm/printf.s
[ 28%] Building CXX object CMakeFiles/sos_kernel.dir/src/blinkingcursor.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/blinkingcursor.cpp.o -c /home/zzp/sos-master/src/blinkingcursor.cpp
[ 35%] Building CXX object CMakeFiles/sos_kernel.dir/src/driver.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/driver.cpp.o -c /home/zzp/sos-master/src/driver.cpp
[ 42%] Building CXX object CMakeFiles/sos_kernel.dir/src/gdt.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/gdt.cpp.o -c /home/zzp/sos-master/src/gdt.cpp
[ 50%] Building CXX object CMakeFiles/sos_kernel.dir/src/interrupts.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/interrupts.cpp.o -c /home/zzp/sos-master/src/interrupts.cpp
[ 57%] Building CXX object CMakeFiles/sos_kernel.dir/src/kernel.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/kernel.cpp.o -c /home/zzp/sos-master/src/kernel.cpp
[ 64%] Building CXX object CMakeFiles/sos_kernel.dir/src/keyboard.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/keyboard.cpp.o -c /home/zzp/sos-master/src/keyboard.cpp
[ 71%] Building CXX object CMakeFiles/sos_kernel.dir/src/mouse.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/mouse.cpp.o -c /home/zzp/sos-master/src/mouse.cpp
[ 78%] Building CXX object CMakeFiles/sos_kernel.dir/src/pci.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/pci.cpp.o -c /home/zzp/sos-master/src/pci.cpp
[ 85%] Building CXX object CMakeFiles/sos_kernel.dir/src/port.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/port.cpp.o -c /home/zzp/sos-master/src/port.cpp
[ 92%] Building CXX object CMakeFiles/sos_kernel.dir/src/screenmanager.cpp.o
/usr/bin/g++   -I/home/zzp/sos-master/build -I/home/zzp/sos-master -I/home/zzp/sos-master/include  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector   -std=gnu++11 -o CMakeFiles/sos_kernel.dir/src/screenmanager.cpp.o -c /home/zzp/sos-master/src/screenmanager.cpp
[100%] Linking CXX executable sos_kernel
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/sos_kernel.dir/link.txt --verbose=1
/usr/bin/g++  -Wall -m32 -nostdlib -fno-use-cxa-atexit -fno-builtin -fno-leading-underscore -fno-rtti -fno-exceptions -fno-stack-protector  -T /home/zzp/sos-master/linker.ld CMakeFiles/sos_kernel.dir/asm/interrupt_stubs.s.o CMakeFiles/sos_kernel.dir/asm/loader.s.o CMakeFiles/sos_kernel.dir/asm/printf.s.o CMakeFiles/sos_kernel.dir/src/blinkingcursor.cpp.o CMakeFiles/sos_kernel.dir/src/driver.cpp.o CMakeFiles/sos_kernel.dir/src/gdt.cpp.o CMakeFiles/sos_kernel.dir/src/interrupts.cpp.o CMakeFiles/sos_kernel.dir/src/kernel.cpp.o CMakeFiles/sos_kernel.dir/src/keyboard.cpp.o CMakeFiles/sos_kernel.dir/src/mouse.cpp.o CMakeFiles/sos_kernel.dir/src/pci.cpp.o CMakeFiles/sos_kernel.dir/src/port.cpp.o CMakeFiles/sos_kernel.dir/src/screenmanager.cpp.o  -o sos_kernel 
mkdir -p iso/boot/grub
cp sos_kernel iso/boot
echo 'set timeout=0' >> iso/boot/grub/grub.cfg
echo 'set default=0' >> iso/boot/grub/grub.cfg
echo '' >> iso/boot/grub/grub.cfg
echo 'menuentry sbw\ OS {' >> iso/boot/grub/grub.cfg
echo ' multiboot /boot/sos_kernel' >> iso/boot/grub/grub.cfg
echo ' boot' >> iso/boot/grub/grub.cfg
echo '}' >> iso/boot/grub/grub.cfg
grub-mkrescue --output=sos.iso iso
xorriso 1.4.2 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:sos.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 29.9g free
Added to ISO image: directory '/'='/tmp/grub.9zWTaI'
xorriso : UPDATE : 279 files added in 1 seconds
Added to ISO image: directory '/'='/home/zzp/sos-master/build/iso'
xorriso : UPDATE : 283 files added in 1 seconds
ISO image produced: 4438 sectors
Written to medium : 4438 sectors at LBA 0
Writing to 'stdio:sos.iso' completed successfully.

rm -rf iso
make[2]: Leaving directory '/home/zzp/sos-master/build'
[100%] Built target sos_kernel
make[1]: Leaving directory '/home/zzp/sos-master/build'
/usr/local/bin/cmake -E cmake_progress_start /home/zzp/sos-master/build/CMakeFiles 0

**Comment by ghost** [comment]
前面一个是cmake的输出，后面是make 的输出。我看好像没有什么问题。但是虚拟机会说没有可以启动的设备文件

**Comment by ghost** [comment]
![screenshot from 2018-07-27 20-28-05](https://user-images.githubusercontent.com/30102054/43320633-aa9e4f56-91db-11e8-997d-7ce5201434e0.png)

**Comment by sbwtw** [comment]
@zhangzp9970 
我看到有 `echo 'menuentry sbw\ OS {' >> iso/boot/grub/grub.cfg` 这样的，这里面 sbw 后面的 \ 应该是多余的，不过这个似乎影响不大。
可以尝试 pull 一下最新代码，重新编译后，按 readme 里面，用 `qemu-system-x86_64 -boot d -cdrom sos.iso -m 512` 来启动 qemu 试试。
另外 ubuntu 上的 qemu 似乎自动加载了某些东西，因为我看到有网络启动相关的，不知道和这个有关没...

**Comment by ghost** [comment]
我看了一下，那个sbw\ 应该是转义空格生成的，我修改成sbwos后还是不行。我发现生成的镜像文件无法被挂载。有可能是镜像文件不对。但是我单独执行了一遍grub-mkrescue貌似并没有什么问题

**Comment by ghost** [comment]
xorriso 1.4.2 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:sos.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 30.1g free
Added to ISO image: directory '/'='/tmp/grub.hMvZhW'
xorriso : UPDATE : 279 files added in 1 seconds
Added to ISO image: directory '/'='/home/zzp/Desktop/sos/build/iso'
xorriso : UPDATE : 283 files added in 1 seconds
ISO image produced: 4440 sectors
Written to medium : 4440 sectors at LBA 0
Writing to 'stdio:sos.iso' completed successfully.

**Comment by sbwtw** [comment]
[sos.zip](https://github.com/sbwtw/sos/files/2237678/sos.zip)
这个是我自己编译出来的 iso，你可以试试，或者把你的 iso 上传一下我试试看

**Comment by ghost** [comment]
[sos.tar.gz](https://github.com/sbwtw/sos/files/2237740/sos.tar.gz)

**Comment by zhangzp9970** [comment]
[sos.tar.gz](https://github.com/sbwtw/sos/files/2237740/sos.tar.gz)

**Comment by ghost** [comment]
我看了一下镜像里面的内容，我发现我的/boot/grub里面没有i386-efi等。只有x86_64-efi文件夹。是不是这个原因。64位的grub没法引导32位系统

**Comment by sbwtw** [comment]
@zhangzp9970 参考 https://github.com/Microsoft/WSL/issues/807 应该是你的机器上没有装 grub，检查 `/usr/lib/grub/i386-pc` 这个目录是否存在。
另外我也会加上 grub 到 build 依赖里面 :)

**Comment by ghost** [comment]
是的，谢谢。我按照那个issue的说法，安装了grub-pc-bin这个包以后就能用了。
